apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-cleaner
  namespace: edygc1988-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-cleaner
subjects:
  - kind: ServiceAccount
    name: job-cleaner
    namespace: edygc1988-dev
