apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-cleaner
  namespace: edygc1988-dev
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete", "get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "delete", "get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
