apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-cleaner
  namespace: edygc1988-dev
  labels:
    app: job-cleaner
spec:
  # Ejecuta todos los d√≠as a las 2 AM
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: job-cleaner
        spec:
          serviceAccountName: job-cleaner
          restartPolicy: OnFailure
          containers:
            - name: job-cleaner
              image: job-cleaner:latest
              imagePullPolicy: Always
              env:
                - name: NAMESPACE
                  value: "edygc1988-dev"
                - name: DAYS_TO_KEEP
                  value: "7"
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
