apiVersion: batch/v1
kind: Job
metadata:
  name: job-cleaner
  namespace: edygc1988-dev
  labels:
    app: job-cleaner
spec:
  template:
    metadata:
      labels:
        app: job-cleaner
    spec:
      serviceAccountName: job-cleaner
      restartPolicy: OnFailure
      containers:
        - name: job-cleaner
          image: job-cleaner:latest
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: "edygc1988-dev"
            - name: DAYS_TO_KEEP
              value: "7"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
  backoffLimit: 3
